version: '3.1'
services:
  bitwarden_dropbox_backup:
    image: shivpatel/bitwarden_rs_dropbox_backup:latest
    restart: always
    volumes:
      - ./db.sqlite3:/db.sqlite3
    environment:
      - DROPBOX_APP_KEY=xxx
      - DROPBOX_APP_SECRET=xxx
      - DROPBOX_REFRESH_TOKEN=xxx
      - BACKUP_ENCRYPTION_KEY=xxx